### ISSUE TITLE
VPTree.nearestNeighbors doesn't return all neighbors

### ISSUE THREAD

**Issue by anvaka** [Yomguithereal/mnemonist#147]
Here is a simple code to reproduce:

``` js
let tree = new VPTree(euclid, [[-100, -100], [100, 100]]);

// since we have two points in the tree, we expect the first one
// to be the query point itself, and the second one is [-100, -100]
console.log(
  tree.nearestNeighbors(2, [100, 100]).length === 2
);

// Instead we get just one point [100, 100]...

function  euclid(a, b) {
  var dx = b[0] - a[0], dy = b[1] - a[1];
  return Math.sqrt(dx * dx + dy * dy)
}
```

**Comment by Yomguithereal** [comment]
Hello @anvaka, thanks for the report, I think I see where things went wrong, I should be able to fix this soon. This said, I would not say this index is a good fit for euclidean distance as some more typical spatial indices should be able to perform this kind of queries more efficiently, except if you have a very multimodal distribution of points in space. In general I was very disappointed with this structure as it is of course affected by the high-dimensionality curse and in my original use cases about Levenshtein metric space, the intrinsic dimensionality of most datasets is usually pretty high. Just my two cents :)

**Comment by Yomguithereal** [comment]
Hello @anvaka, I am currently fixing the issue and before adding some optimization related to cases when you are querying `k` nearest neighbors >= to the number of items I'd like your insight on this part of the commit: https://github.com/Yomguithereal/mnemonist/commit/758841e58fcfef8f18b3f2f33033c7fdb8282e03#diff-c8d7455bfaac71927df4d307bc2fd4bc25b15e9cc98c88d7b482012c9876f6a5R207-R209

It seems to me this is the way to fix the issue but I could not find any implementation of the structure which is not affected by the same problem because of not updating tau before the heap is full.
