### ISSUE TITLE
ESModule support

### ISSUE THREAD

**Issue by hoangvvo** [Yomguithereal/mnemonist#169]
Hi, I think it would be a good idea for this library to support ESModule for easier consumption.

There are several strategies I can think of right:

- Support both ESModule and commonjs by letting both `.mjs` and `.js` live together (gitignore the commonjs versions). We will use use [Conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports) to select the appropriate version. Old version of Node can fallback to the commonjs `.js` version.
- Drop support of commonjs in a breaking version, optionally maintain support it via a different npm dist tag (eg. `v1.3.5-cjs`) We will have to set up a pipeline to combine `mjs` to `js` and publish it seperately.

I would love to open a PR for this after we decide on a way. Thanks!

**Comment by Yomguithereal** [comment]
Hello @hoangvvo. Breaking is not an option here. So we would need to go with your first option, with some tweaks: gitignore the mjs version instead, which therefore needs to be built from the commonjs files using some tool like rollup for instance? This should be painless because the library does not use the commonjs trick to have both default and named exports. Note also that people rarely import this library through its endpoint but rather one structure at a time and I don't know if conditional exports work for this case (I guess they fallback to chosing the `.js` or `.mjs` file, but I did not follow the latest commonjs vs. ES6 import node kerfuffle lately).
