### ISSUE TITLE
MultiSet.toJSON output is surprising

### ISSUE THREAD

**Issue by kberg** [Yomguithereal/mnemonist#204]
Granted, it's not documented, but...

```
const s = new MultiSet<string>();
s.add('a', 2);
console.log(s.get('a'));
console.log(JSON.stringify(s.toJSON()));
```

generates

```
2
{}
```

I expected something like

```
2
{a: 2}
```

**Comment by kberg** [comment]
PS

```
console.log(JSON.stringify(Array.from(s.toJSON())));
```
generates
```
[["a",2]]
```

**Comment by Yomguithereal** [comment]
Hello @kberg, this follows the same weird (but explainable) behavior than an ES6's Set. Try for instance:

```js
JSON.stringify(new Set([2]));
// By the way, JSON.stringify automatically calls any toJSON method for you
```

The reason is that you could use arbitrary keys, even keys that are not JSON-serializable. To this end, ES6 does not JSON-stringifies Set nor Map and ask you to define how you want to do it, a bit like you are doing with your second example that serializes the entries of the multiset.

**Comment by kberg** [comment]
I see. What's the value of toJSON, then?

**Comment by kberg** [comment]
(You can ignore my question if you like.)

**Comment by Yomguithereal** [comment]
> I see. What's the value of toJSON, then?

In this particular case (the MultiSet) one, not much I am afraid. I just replicated ES6's one in case the specs would change (at that time it was still possible).

The fact is there is no way to serialize some things with JSON and a Set that would rely on object references is one.
