### ISSUE TITLE
Unsure about toJSON returning Uint32Array

### ISSUE THREAD

**Issue by DavidBruant** [Yomguithereal/mnemonist#82]
`toJSON` might be used in [JSON.stringify](https://www.ecma-international.org/ecma-262/#sec-serializejsonproperty) and I'm not sure it would yield the proper result

https://github.com/Yomguithereal/mnemonist/blob/master/bit-set.d.ts#L28

**Comment by Yomguithereal** [comment]
The typing is correct. The intention is probably less so since JSON serialization of typed array yields silly results. I guess I should probably fix the method and return an array of zeros and one. I need to add proper serialization to base64 or raw bytes etc. since using raw JSON arrays to store a bitset is basically stupid :)

**Comment by DavidBruant** [comment]
> since using raw JSON arrays to store a bitset is basically stupid

An array of 32-bit ints might be more appropriate ;-)

If the intention is serialization, you may want to look into protocol buffers or something like that (or let people send the binary format)

**Comment by Yomguithereal** [comment]
I will export to 32-bit ints right now and add a toString that emits a string such as '01110101110'. I don't want to stick to a specific binary format such as protobuf or msgpack since I want people to remain free to use whichever they want. I will just need to make sure they can easily and performant-ly do so.
